on: push
name: Build and deploy on push
jobs:
  build:
    name: deploy_all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@1d42d36830353a145f297e9225b6f3c6f133bc46
        env:
          PAGES_BRANCH: gh-pages
          BUILD_FLAGS: --drafts
          TOKEN: ${{ secrets.TOKEN }}
