on:
  push:
    branches:
      - main, gh-pages
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Build only'
        uses: shalzz/zola-deploy-action@1d42d36830353a145f297e9225b6f3c6f133bc46
        env:
          BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}
          BUILD_ONLY: true
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@1d42d36830353a145f297e9225b6f3c6f133bc46
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}
